FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:$PORT

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["backend/PortfolioApp/PortfolioApp.csproj", "backend/PortfolioApp/"]
WORKDIR "/src/backend/PortfolioApp"
RUN dotnet restore "PortfolioApp.csproj"
COPY . .
RUN dotnet build "PortfolioApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PortfolioApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PortfolioApp.dll"]
