# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln .
COPY PortfolioAPI/*.csproj ./PortfolioAPI/
RUN dotnet restore

COPY PortfolioAPI/. ./PortfolioAPI/
WORKDIR /app/PortfolioAPI
RUN dotnet publish -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/PortfolioAPI/out ./
ENV ASPNETCORE_URLS=http://+:${PORT}
EXPOSE 10000
ENTRYPOINT ["dotnet", "PortfolioAPI.dll"]