// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbnjmvlfcplfvlriwdab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibmptdmxmY3BsZnZscml3ZGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjcyMDcsImV4cCI6MjA2NTcwMzIwN30.zbeUJCZ-uj7j0Wh3L5M6vtcYpJ5YawC8dk0rP3N98zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);